#!/usr/bin/env python3.7

from jinja2 import Environment, FileSystemLoader, select_autoescape
from pathlib import Path
import json
import re
import sys

def deserialize_json(name):
    """ Deserealize a json file given as padding document 
        Information retrieves from it is used to fill in
        jinja templates
    
    :param name: name of padding document
    """
    if Path(name).suffix != '.json':
        raise Exception(name)
    with open(name, "r") as file:    
        des_json = json.load(file)
    return des_json
    

if __name__ == "__main__":
    abs_path = Path.cwd()
    print(abs_path)
    padding_doc = sys.argv[1]
    template_doc = sys.argv[2]

    print(f"Padding:{padding_doc}")
    print(f"Template:{template_doc}")

    env = Environment(
        loader=FileSystemLoader(str(abs_path.joinpath('templates'))),
        autoescape=select_autoescape(['ncl', 'xml']),
        trim_blocks=True,
        lstrip_blocks=True
    )

    #TODO:find a way to pass the 'younger' child template
    template = env.get_template(template_doc)

    try:
        context = {'files_list': deserialize_json(padding_doc)}
    except Exception as e:
        msg  = "Error: Padding document '{e}' in wrong format".format(e=e.args[0])
        print (msg)
    else:
        content = template.render(context)
        path = abs_path.joinpath('slideShow.ncl')   
        with open(path , "w") as file:
            file.write(content)
        print("Ended")
